---
common_packages:
  - net-tools
  - mc
  - dstat
  - htop
  - curl
  - wget
  - vim
  - jq
  - lsof
  - iotop
  - tcpdump
  - unzip
  - git
  - apt-transport-https
  - ca-certificates
  - gnupg
  - pciutils
  - python3-pip
  - nfs-common
  - cifs-utils
