apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: untrusted-project
  namespace: argocd
spec:
  destinations:
    - namespace: untrusted
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - { group: "",                   kind: ConfigMap }
    - { group: "",                   kind: Secret }
    - { group: "",                   kind: Service }
    - { group: "",                   kind: ServiceAccount }
    - { group: "",                   kind: PersistentVolumeClaim }
    - { group: apps,                 kind: Deployment }
    - { group: apps,                 kind: StatefulSet }
    - { group: batch,                kind: Job }
    - { group: batch,                kind: CronJob }
    - { group: networking.k8s.io,    kind: Ingress }
  namespaceResourceBlacklist:
    - { group: rbac.authorization.k8s.io, kind: Role }
    - { group: rbac.authorization.k8s.io, kind: RoleBinding }
    - { group: networking.k8s.io,         kind: NetworkPolicy }
    - { group: cilium.io,                 kind: CiliumNetworkPolicy }
