apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policy.yaml
- appproject.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - clusterrole-storage.yaml
  - monitoring-namespace.yaml
  - monitoring-victoria-metrics.yaml
  - monitoring-node-exporter.yaml
  - monitoring-grafana-password.yaml
  - monitoring-grafana.yaml
  - monitoring-grafana-dashboard.yaml
  - monitoring-dcgm-exporter.yaml
  - monitoring-dcgm-dashboard.yaml
  - monitoring-networkpolicy.yaml
  - smb-csi-application.yaml
  - smb-storageclass.yaml
  - port-proxy-namespace.yaml
  - port-proxy-rsync.yaml
